# Default values for edge-normalization.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renciorg/edgenormalization
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
