apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
    app-name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "robokop-ui-v2.selectorLabels" . | nindent 6 }}
      app-name: frontend
  template:
    metadata:
      labels:
        {{- include "robokop-ui-v2.selectorLabels" . | nindent 8 }}
        app-name: frontend
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
