apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-messenger-dep
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
    app-name: messenger
spec:
  selector:
    matchLabels:
      {{- include "robokop-ui-v2.selectorLabels" . | nindent 6 }}
      app-name: messenger
  template:
    metadata:
      labels:
        {{- include "robokop-ui-v2.selectorLabels" . | nindent 8 }}
        app-name: messenger
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-messenger-init-container
          image: "{{ .Values.messenger.image.repository }}:{{ .Values.messenger.image.tag }}"
          command:
            - "git"
          args:
            - "clone"
            - "https://github.com/NCATS-Gamma/robokop-messenger.git"
          volumeMounts:
            - mountPath: /home/murphy/
              name: code-dir
      containers:
        - name: {{ .Chart.Name }}-messenger-container
          image: "{{ .Values.messenger.image.repository }}:{{ .Values.messenger.image.tag }}"
          env:
            - name: NEO4J_USER
              value: {{ .Values.neo4j.username  | quote }}
            - name: NEO4J_PASSWORD
              value: {{ .Values.neo4j.password  | quote }}
            - name: CACHE_HOST
              value: {{ .Values.messenger.cacheHost | quote }}
            - name: CACHE_PORT
              value: {{ .Values.messenger.cachePort | quote }}
            - name: CACHE_DB
              value: "0"
            - name: CACHE_PASSWORD
              value: {{ .Values.messenger.cachePassword | quote }}
            - name: PYTHONPATH
              value: "/home/murphy/robokop-messenger"
            - name: NEO4J_URL
              value: "http://{{ include "robokop-ui-v2.fullname" . }}-neo4j-service:{{ .Values.neo4j.service.httpPort }}"
            - name: OMNICORP_USER
              value: {{ .Values.messenger.omnicorpUser | quote}}
            - name: OMNICORP_PASSWORD
              value: {{ .Values.messenger.omnicorpPassword | quote }}
            - name: OMNICORP_DB
              value: {{ .Values.messenger.omnicorpDB | quote }}
            - name: OMNICORP_HOST
              value: {{ .Values.messenger.omnicorpHost | quote }}
            - name: OMNICORP_PORT
              value: {{ .Values.messenger.omnicorpPort | quote }}
          command:
            - "gunicorn"
          args:
            - "--bind"
            - "0.0.0.0:{{ .Values.messenger.service.port }}"
            - "-w"
            - "4"
            - "-k"
            - "uvicorn.workers.UvicornWorker"
            - "-t"
            - "600"
            - "messenger.server:APP"
          ports:
          - name: http
            containerPort: {{ .Values.messenger.service.port }}
            protocol: TCP
          volumeMounts:
            - mountPath: /home/murphy
              name: code-dir
      restartPolicy: Always
      volumes:
        - name: code-dir
          emptyDir: {}