apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-ui-proxy
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
    app-name: ui-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "robokop-ui-v2.selectorLabels" . | nindent 6 }}
      app-name: ui-proxy
  template:
    metadata:
      labels:
        {{- include "robokop-ui-v2.selectorLabels" . | nindent 8 }}
        app-name: ui-proxy
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: dnsmasq
          image: "janeczku/go-dnsmasq:release-1.0.7"
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
        - name: proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          env:
            - name: DNS_SERVER
              value: 127.0.0.1
            - name: FRONTEND_URL
              value: http://{{ include "robokop-ui-v2.fullname" . }}-frontend:{{ .Values.frontend.service.port }}
            - name: ROBOKACHE_URL
              value: http://{{ include "robokop-ui-v2.fullname" . }}-robokache:{{ .Values.robokache.service.port }}
            - name: QUERYDISPATCHER_URL
              value: http://{{ include "robokop-ui-v2.fullname" . }}-query-dispatcher:{{ .Values.queryDispatcher.service.port }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http