apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-query-dispatcher
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
    app-name: query-dispatcher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "robokop-ui-v2.selectorLabels" . | nindent 6 }}
      app-name: query-dispatcher
  template:
    metadata:
      labels:
        {{- include "robokop-ui-v2.selectorLabels" . | nindent 8 }}
        app-name: query-dispatcher
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: query-dispatcher
          image: "{{ .Values.queryDispatcher.image.repository }}:{{ .Values.queryDispatcher.image.tag }}"
          imagePullPolicy: {{ .Values.queryDispatcher.image.pullPolicy }}
          env:
            - name: ROBOKACHE_URL
              value: "http://{{ include "robokop-ui-v2.fullname" . }}-robokache:{{ .Values.robokache.service.port }}"
            - name: MESSENGER_HOST
              value: "http://{{ include "robokop-ui-v2.fullname" . }}-messenger:{{ .Values.messenger.service.port }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP