apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-robokache-statefulset
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
    app-name: robokache
spec:
  serviceName: robokache
{{/*{{ include "robokop-ui-v2.fullname" . }}-service*/}}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "robokop-ui-v2.selectorLabels" . | nindent 6 }}
      app-name: robokache
  template:
    metadata:
      labels:
        {{- include "robokop-ui-v2.selectorLabels" . | nindent 8 }}
        app-name: robokache
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-robokache
          image: "{{ .Values.robokache.image.repository }}:{{ .Values.robokache.image.tag }}"
          imagePullPolicy: {{ .Values.robokache.image.pullPolicy }}
          env:
            - name: ROBOKACHE_DATA_DIR
              value: {{ .Values.robokache.dataDir }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.robokache.dataDir }}
              name: {{ include "robokop-ui-v2.fullname" . }}-robokache-data-volume
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: {{ include "robokop-ui-v2.fullname" . }}-robokache-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.robokache.storageSize }}
