apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-frontend
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ui-v2.selectorLabels" . | nindent 4 }}
    app-name: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-robokache
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.robokache.service.type }}
  ports:
    - port: {{ .Values.robokache.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ui-v2.selectorLabels" . | nindent 4 }}
    app-name: robokache
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-query-dispatcher
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.queryDispatcher.service.type }}
  ports:
    - port: {{ .Values.queryDispatcher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ui-v2.selectorLabels" . | nindent 4 }}
    app-name: query-dispatcher

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-proxy
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ui-v2.selectorLabels" . | nindent 4 }}
    app-name: ui-proxy

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-neo4j-service
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neo4j.service.type }}
  ports:
    - port: {{ .Values.neo4j.service.httpPort }}
      targetPort: neo4j-http
      protocol: TCP
      name: http
    - port: {{ .Values.neo4j.service.httpsPort  }}
      targetPort: neo4j-https
      protocol: TCP
      name: https
    - port: {{ .Values.neo4j.service.boltPort  }}
      targetPort: neo4j-bolt
      protocol: TCP
      name: bolt
  selector:
    {{- include "robokop-ui-v2.selectorLabels" . | nindent 4 }}
    app-name: neo4j

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-messenger
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.messenger.service.type }}
  ports:
    - port: {{ .Values.messenger.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ui-v2.selectorLabels" . | nindent 4 }}
    app-name: messenger
