apiVersion: v1
kind: Service
metadata:
  name: {{ include "translator-workflow-runner.fullname" . }}-web-service
  labels:
    {{- include "translator-workflow-runner.labels" . | nindent 4 }}
spec:
  {{- include "translator-workflow-runner.serviceDefinition" . | nindent 2}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port}}
      protocol: TCP
      name: http
  selector:
    app: {{ include "translator-workflow-runner.name" . }}
