apiVersion: v1
kind: Service
metadata:
  name: {{ include "plater.fullname" . }}
  labels:
    {{- include "plater.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.app.neo4j.httpPort }}
      targetPort: {{ .Values.app.neo4j.httpPort }}
      protocol: TCP
      name: neo4j-http
    - port: {{ .Values.app.neo4j.boltPort }}
      targetPort: {{ .Values.app.neo4j.boltPort }}
      protocol: TCP
      name: neo4j-bolt
  selector:
    {{- include "plater.selectorLabels" . | nindent 4 }}