apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plater.fullname" . }}-plate
  labels:
    {{- include "plater.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "plater.selectorLabels" . | nindent 6 }}
      service-type: web-server
  template:
    metadata:
      labels:
        {{- include "plater.selectorLabels" . | nindent 8 }}
        service-type: web-server
    spec:
      initContainers:
        - name: {{ include "plater.fullname" . }}-init-container
          image: busybox
          command:
            - './check_neo.sh'
          env:
            - name: NEO4J_HOST
              value: {{ include "plater.fullname" . }}-neo4j-service
            - name: NEO4J_HTTP_PORT
              value: "{{ .Values.app.neo4j.httpPort }}"
          volumeMounts:
            - name: {{ include "plater.fullname" . }}-init-container-volume
              mountPath: /check_neo.sh
              subPath: check_neo.sh
      containers:
        - name: {{ include "plater.fullname" . }}-web-container
          image: "{{ .Values.image.plater.repository }}:{{ .Values.image.plater.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: WEB_HOST
              value: "0.0.0.0"
            - name: WEB_PORT
              value: "{{ .Values.app.port }}"
            - name: NEO4J_HOST
              value: {{ include "plater.fullname" . }}-neo4j-service
            - name: NEO4J_PASSWORD
              value: "{{ .Values.app.neo4j.password }}"
            - name: NEO4J_HTTP_PORT
              value: "{{ .Values.app.neo4j.httpPort }}"
            - name: NEO4J_USERNAME
              value: "{{ .Values.app.neo4j.username }}"
            - name: PLATER_SERVICE_ADDRESS
              value: "{{ include "plater.fullname" . }}-plater-service"
          args:
            - -a
            - {{ .Values.app.automatAddress }}
            - {{ .Release.Name }}
      volumes:
        - name: {{ include "plater.fullname" . }}-init-container-volume
          configMap:
            name: {{ include "plater.fullname" . }}-configmap
            defaultMode: 0777

