# Default values for aragorn-ranker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: renciorg/aragorn-ranker
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  host: ########HOSTNAME#######
  class: ####Ingress class#####

app:
  port: 8080