apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "answer-coalesce.fullname" . }}-redis-config
data:
  config.json: |-
    {
    "redis_host": "{{ include "answer-coalesce.fullname" . }}-redis-service",
    "redis_port": {{ .Values.redis.service.port }},
    "redis_password": "",
    "test_mode": 0
    }