apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tranql_backplane.deployment_name }}
  labels:
    service: {{ .Values.tranql_backplane.service_name }}
    app: {{ .Values.tranql_backplane.app_name }}
spec:
  replicas: {{ .Values.tranql_backplane.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tranql_backplane.app_name }}
  template:
    metadata:
      labels:
        app: tranql-backend
    spec:
      volumes:
        - name: {{ .Values.tranql_logs.container_volume_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.tranql_logs.pvc_name }}
{{ if .Values.env.dev }}
        - name: code-dir
          emptyDir: {}
{{ end }}
      terminationGracePeriodSeconds: 10
{{ if .Values.env.dev }}
      initContainers:
        - name: tranql-init-container
          image: alpine/git
          volumeMounts:
            - mountPath: /git/tranql
              name: code-dir
          command:
            - /bin/sh
            - -c
          args:
            - "git clone --single-branch --branch {{ if .Values.env.branch }} {{ .Values.env.branch }} {{ else }} master {{ end }} https://github.com/NCATS-Tangerine/tranql.git "
{{ end }}
      containers:
      - name: tranql-backplane
        image: {{ .Values.tranql_backplane.image }}:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        command: [ "/usr/local/bin/gunicorn", "--worker-class=gevent","--workers=3", "--timeout={{ .Values.timeout }}", "--access-logfile=$(ACCESS_LOG)", "--error-logfile=$(ERROR_LOG)", "--log-level=debug", "tranql.backplane.server:app" ]
        ports:
          - containerPort: {{ .Values.tranql_backplane.web_app_port }}
            name: http
        env:
          - name: BACKPLANE_PORT
            value: {{ .Values.tranql_backplane.web_app_port | quote }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACCESS_LOG
            value: "/var/nfs/tranql-backplane_access_log"
          - name: ERROR_LOG
            value: "/var/nfs/tranql-backplane_error_log"
          - name: ROBOKOP_MAX_RESULTS
            value: "{{ .Values.robokopOptions.maxAnswers }}"
          - name: ROBOKOP_MAX_CONNECTIVITY
            value: "{{ .Values.robokopOptions.maxNodeConnections }}"
        volumeMounts:
          - name: {{ .Values.tranql_logs.container_volume_name }}
            mountPath: /var/nfs
{{ if .Values.env.dev }}
          - mountPath: /tranql
            name: code-dir
{{ end }}
      restartPolicy: {{ .Values.tranql_backplane.restart }}
