
redisImage:
  repository: redis
  tag: latest

webserverImage:
  repository: renciorg/r3_nodenorm
  tag: latest
    # options are renciorg/r3_nodenorm or renciorg/r3_chemnorm

redis:
  service:
    type: ClusterIP
  port: 6379
  resources:
    limits:
      memory: 100Mi
    requests:
      memory: 100Mi
  seedDB: true
  storage:
    size: 20Mi
web:
  replicaCount: 1
  service:
    type: NodePort
  port: 6380




