redisImage:
  repository: redis
  tag: latest

webserverImage:
  repository: renciorg/r3_nodenorm
  tag: 1.0.7
    # options are renciorg/r3_nodenorm or renciorg/r3_chemnorm

redis:
  service:
    type: ClusterIP
  port: 6379
  resources:
    limits:
      memory: 256Gi
    requests:
      memory: 256Gi
  seedDB: false
  storage:
    size: 100Gi
  args:
   - --save
   - ''
   - --stop-writes-on-bgsave-error
   - 'no'
web:
  replicaCount: 1
  service:
    type: ClusterIP
  port: 6380

ingress:
  host: HOST-NAME
  class: Ingress-class-name