
redisImage:
  repository: redis
  tag: latest

webserverImage:
  repository: renciorg/r3_nodenorm
  tag: latest
    # options are renciorg/r3_nodenorm or renciorg/r3_chemnorm

redis:
  service:
    type: ClusterIP
  port: 6379
  resources:
    limits:
      memory:
    requests:
      memory:
  seedDB: true
  storage:
    size: # enter storage size here
  storageclass: translator-node-normalization-sc
  pvcName: translator-node-normalization-pvc
web:
  replicaCount: 1
  service:
    type: NodePort
  port: 6380
createPVC: false
createPV: false


