apiVersion: v1
kind: Service
metadata:
  name: {{ include "biolink-lookup.fullname" . }}
  labels:
    {{- include "biolink-lookup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8144
      protocol: TCP
      name: http
  selector:
    {{- include "biolink-lookup.selectorLabels" . | nindent 4 }}
