{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "robokop.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
         serviceName: {{ include "robokop.fullname" . }}-nginx-proxy-service
         servicePort: {{ .Values.nginxProxy.port }}
{{- end }}
