{{- if .Values.knowledgeGraph.createPVC}}
apiVersion: v1
items:
  {{- if .Values.knowledgeGraph.createPV }}
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: {{ include "robokop.fullname" . }}-knowledge-graph-pv
  spec:
    accessModes:
      - ReadWriteOnce
    capacity:
      storage: {{ .Values.knowledgeGraph.storageSize }}
    persistentVolumeReclaimPolicy: Retain
    storageClassName: {{ include "robokop.fullname" . }}-knowledge-graph-pv-sc
  {{- end }}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: {{ .Values.knowledgeGraph.pvcName }}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.knowledgeGraph.storageSize }}
    {{- if .Values.knowledgeGraph.createPV }}
    storageClassName: {{ include "robokop.fullname" . }}-knowledge-graph-pv-sc
    {{- end }}
kind: List
{{- end}}