# Default values for plater.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  plater:
    repository: renciorg/plater
    tag: latest
  neo4j:
    repository: renciorg/neo4jkp
    tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
app:
  port: 8080
  automatAddress: http://automat
  neo4j:
    httpPort: 7474
    boltPort: 7687
    password: neo4jkp
    username: neo4j
    # These are jvm based values hence suffix with one of the following G, M etc...
    heapsize: 1G
    pageCacheSize: 200M
    # this is kubernetes value, valid suffixes are Gi, Mi etc...
    # It's used to request the cluster for memory capable of running neo4j per the heap and PageCache values above
    # Compute this value by summing up heapSize + pageCacheSize + (200Mi for os of the image)
    totalMemory: 1.4Gi
    storage:
      size: 20Mi
      pvName:
      # Uncomment the following to use nfs.
#      nfs:
#        server: # Put server address here
      # Put dir of path containing neo4j_data/  prepopulated with contents of a neo4j instance data/ dir
      path:
    service:
      type: ClusterIP
    seedDB: true
createPV: true