# Default values for biolink-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renciorg/bl_lookup
  tag: latest

service:
  type: NodePort
  port: 80