# Default values for robokop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

adminEmail: ##############

omnicorpPostgres:
  image:
    repository: postgres
    tag: 11
  port: 5432
  serviceType: ClusterIP
  dbName: robokop
  dbUser: murphy
  pvcName: ####REQUIRED####
  createPVC: false
  createPV: false
  storageSize: ####REQUIRED_IF_CREATEPVC_TRUE####

ranker:
  image:
    repository: renciorg/robokop_ranker
    tag: "2.0"
  serviceType: ClusterIP
  port: 6011
  supervisorPort: 9003

manager:
  image:
    repository: renciorg/robokop_manager
    tag: latest
  serviceType: ClusterIP
  webPort: 8080
  supervisorPort: 9001
  graphQLPort: 6498
  pubmedCache:
    image: redis:latest
    port: 6382
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 200Mi
  # Memory config for postgraphile
  nodeJS:
    # Node server accepts size in MB only (https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes)
    nodeMemory: "8192" #####REQUIRED(eg nodeMemory: 8192)####
    # adjust following values as appropriate give 1G for there process running in
    # manager container, to avoid swapping
    resources:
      requests:
        memory: "9G" ####REQUIRED####
      limits:
        memory: "9G" ####REQUIRED####
  postgres:
    image: postgres:10
    port: 5432
    pvcName: ##############
    createPV: false
    createPVC: false
    storageSize: 10Mi

messenger:
  image:
    repository: renciorg/robokop_messenger
    tag: "2.0"
  serviceType: ClusterIP
  port: 4868

backendServices:
  serviceType: ClusterIP
  celeryRedis:
    image: redis:latest
    port: 6381
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
  broker:
    image: patrickkwang/robokop-rabbitmq
    webPort: 15672
    amqpPort: 5672
    user: murphy
  nlp:
    image: patrickkwang/robokop-nlp
    port: 9475

interfaces:
  image:
    repository: renciorg/robokop_interfaces
    tag: latest
  port: 6011
  supervisorPort: 9002
  buildCacheImage: redis:latest
  buildCachePort: 6380
  serviceType: NodePort

knowledgeGraph:
  image:
    repository: renciorg/neo4jkp
    tag: latest
  port: 7474
  boltPort: 7687
  pageCacheMemorySize: 17G
  heapMemorySize: 32G
  resources:
    limits:
      memory: 50G # pagecache + heap + 1G os
    requests:
      memory: 50G
  serviceType:  ClusterIP
  createPV: false
  createPVC: false
  pvcName: ##############
  storageSize:
  seedDB: false

requestsCache:
  image:
    repository: redis
    tag: latest
  port: 6380
  serviceType: ClusterIP
  pvcName: ##############
  seedDB: false
  createPV: false
  createPVC: false
  storageSize:
  resources:
    limits:
      memory: 40G
    requests:
      memory: 40G

nginxProxy:
  image:
    repository: nginx
    tag: latest
  port: 80
  serviceType: ClusterIP

logs:
  pvcName: translator-robokop-logs-pvc
  storageSize:
  createPVC: false
  createPV: false

mail:
  server: smtp.mailgun.org
  userName: postmaster@mailer.robokop.org
  robokopEmailAddr: no-reply@mailer.robokop.org


service:
  type: ClusterIP


secrets:
  adminPassword: ##############
  celeryRedisPassword: ##############
  brokerPassword: ##############
  omnicorpPassword: ##############
  postgresPassword: ##############
  pubmedCachePassword: ##############
  supervisorPassword: ##############
  neo4jPassword: ##############
  mailServerPassword: ##############
  appSecretKey: ##############
  appSecretSalt: ##############
  requestsCachePassword: ##############

nameOverride: ""
fullnameOverride: ""


ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: ##############
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


