apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "r3.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName:  {{ include "r3.fullname" . }}-web-service
          servicePort: {{ .Values.web.port }}