apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: {{ include "r3.fullname" . }}-redis-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.redis.storage.size }}
kind: List