apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "automat.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls.hosts }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName:  {{ include "automat.fullname" . }}
          servicePort: {{ .Values.service.port }}