# Default values for name-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

webServer:
  service:
    port: 2433
    type: ClusterIP
  # container port
  port: 2433
  image:
    repository: renciorg/name_lookup
    tag: latest

solr:
  service:
    port: 8983
    type: ClusterIP
  # container port
  port: 8983
  image:
    repository: solr
    tag: latest
  resources:
    requests:
      memory: "5Gi"
    limits:
      memory: "5Gi"

nameOverride: ""
fullnameOverride: ""

ingress:
  host: name-resolution-sri.renci.org
  class: "translator"

