apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aragorn-ranker.fullname" . }}
  labels:
    app: {{ include "aragorn-ranker.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "aragorn-ranker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aragorn-ranker.name" . }}
    spec:
      containers:
        name: {{ .Chart.Name }}-web-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        envFrom:
          - configMapRef:
              name: {{ include "aragorn-ranker.fullname" . }}-configmap
        env:
        - name: WEB_HOST
          value: 0.0.0.0
        - name: WEB_PORT
          value: {{ .Values.app.port | quote}}
        ports:
          - name: http
            containerPort: {{ .Values.app.port }}
            protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
