apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "strider.fullname" . }}-redis-server
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: redis
spec:
  serviceName: {{ include "strider.fullname" . }}-redis-service
  selector:
    matchLabels:
      {{- include "strider.selectorLabels" . | nindent 6 }}
      service-type: redis
  template:
    metadata:
      labels:
        {{- include "strider.selectorLabels" . | nindent 8 }}
        service-type: redis
    spec:
      containers:
        - name: {{ .Chart.Name }}-redis-container
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
        {{- if .Values.redis.args }}
          args:
            {{- range .Values.redis.args }}
            - {{ . | quote }}
            {{- end }}
        {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "strider.fullname" . }}-redis-data-volume
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: {{ include "strider.fullname" . }}-redis-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi