
## Values for tranql frontend
tranql_frontend:
  image: renciorg/tranql-app
  image_tag: latest
  deployment_name: tranql-frontend-deployment
  service_name: tranql-frontend-service
  app_name: tranql_frontend
  replicas: 7
  web_app_port: "8001"
  restart: "Always"
  # Comment the line below to disable registry
  use_kp_registry: true

## Values for tranql backplane
tranql_backplane:
  image: renciorg/tranql-base
  image_tag: latest
  deployment_name: tranql-backend-deployment
  service_name: tranql-backend-service
  app_name: tranql-backend
  replicas: 3
  web_app_port: "8099"
  restart: Always

### Values for log persistence
tranql_logs:
  pv_name: tranql-logs-pv
  pvc_name: tranql-logs-pvc
  container_volume_name: tranql-logs-volume
  storage_size: 1Gi
  createPV: false
  createPVC: true

### Varnish cache configurations
tranql_varnish:
  image: renciorg/tranql-varnish
  image_tag: latest
  port: 8080
  frontend:
    deployment_name: tranql-frontend-cache-dep
    service_name: tranql-frontend-cache-service
    app_name: tranql-frontend-cache
    config_name: tranql-frontend-cache-config
    container_name: tranql-varnish-frontend-container
    cache_ttl: 3h
  backplane:
    deployment_name: tranql-backplane-cache-dep
    service_name: tranql-backplane-cache-service
    app_name: tranql-backend-cache
    config_name: tranql-backplane-cache-config
    container_name: tranql-varnish-backplane-container
    cache_ttl: 3h

# These values will be passed to tranql backplane container
# it can be used to set parameters for quering robokop
robokopOptions:
  maxNodeConnections: "10000"
  maxAnswers: "300"

tranql_artillery:
  image: renciorg/tranql-artillery
  image_tag: latest
timeout: 86400
# the following values will be used to select the entry point from a loadbalancer
# if enable cache is true varnish frontend cache will be the entry point
# else tranql_frontend will be the entrypoint
# and also enable_cache false will make sure that tranql_frontend is routing
# directly to tranql-backplane and not through backplane cache proxy
enable_cache: false
ingress:
#  class: translator
#  backplaneHost: tranql-backplane.renci.org
#  frontEndHost: tranql.renci.org
  class: public
  backplaneHost: tranql-backplane-dev.renci.org
  frontEndHost: tranql-dev.renci.org
  tls:
    hosts:
    - host: tranql-dev.renci.org
      secretName: tranql-dev-tls-secret
    - host: tranql-backplane-dev.renci.org
      secretName: tranql-backplane-dev-tls-secret
env:
  dev: true
  branch: "develop"

