apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "smartbag.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName:  {{ include "smartbag.fullname" . }}
          servicePort: {{ .Values.service.port }}

